# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps: 
- task: DotNetCoreCLI@2
  displayName: Build App2 Web
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Publish App2 Web
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: CopyFiles@2
  displayName: Copy AWS CodeDeploy files
  inputs:
      SourceFolder: 'Deployment'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: S3Upload@1
  displayName: Upload Package to S3
  inputs:  
    awsCredentials: 'App2-S3-Build-Package'
    regionName: 'ap-southeast-2'
    bucketName: 'app2-package'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**'
    targetFolder: 'package-app2'