version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/App2
    
hooks:  
  ApplicationStop:
    - location: ApplicationStop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 60
      runas: root  
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 180
      runas: root